---
title: "TDD Perimeter Function JS"
type: "exercise"  # challenge, exercise, article, video
description: "Lesson Description."
tags: "javascript, functions, jest"
ignore:
- "perimeter-function-js.md"
